### ISSUE TITLE
Add/update streams standard

### ISSUE THREAD

**Issue by domenic** [MicrosoftEdge/Status#108]
There is currently an entry for the defunct streams API. That project has been abandoned in favor of https://github.com/whatwg/streams (see also https://streams.spec.whatwg.org/), which has [some good cross-browser commitment and a close-to-stable spec](http://lists.w3.org/Archives/Public/public-sysapps/2014Jun/0014.html).

It would be great to add a new entry, or update the existing entry, to reflect this change, and Microsoft's interest in it.

(It would also be great to get something more than the generic "Under Consideration," which seems to mean "we don't hate it" instead of "it's in our backlog". But that's a larger issue.)

**Comment by sideshowbarker** [comment]
Domenic is correct here. We do not have an active editor for the https://dvcs.w3.org/hg/streams-api/raw-file/tip/Overview.htm document, and it’s not been updated in more than 10 months, so we rightly should just be moving it to a Note at this point, and just redirecting the ED URL to the https://streams.spec.whatwg.org/ spec. I sent a note to Art Barstow saying at much https://lists.w3.org/Archives/Public/public-webapps/2015JulSep/0308.html and will follow up with him and the WebApps WG team contacts about dealing with getting that done as soon as possible.

But getting the URL updated here as Domenic proposed should not wait on those things getting done, because in the time, the current reference is misleading and confusing—especially to implementors of other UAs who do consult this page with the expectation that it has accurate information.

**Comment by jacobrossi** [comment]
Sorry, guys, that this got dropped.  Given there isn't a W3C spec that's being maintained, I'll update this to the WhatWG spec.

**Comment by sideshowbarker** [comment]
> Sorry, guys, that this got dropped. Given there isn't a W3C spec that's being maintained, I'll update this to the WhatWG spec.

Cool. FYI I’ve also gone ahead and put warning disclaimers on the W3C Streams ED and WD to make it more clear that those are out of date at this point.
