### ISSUE TITLE
UserVoice Stars Are Not Up To Date

### ISSUE THREAD

**Issue by phistuck** [MicrosoftEdge/Status#181]
https://status.modern.ie/shapes?term=shapes
Says CSS Shapes have 26 stars, despite linking to -
https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6263716-shapes
That shows 303 votes (votes are stars, right?).

:(

**Comment by molant** [comment]
I see 303 in the website. Votes get updated every 15 minutes via an Azure Webjob. Usually when there is a deployment we force a download but there could be a moment or two where the values are incorrect (time to invoke the webjob, let it do its work and update the content) so that could be the problem you've seen.

**Comment by phistuck** [comment]
It is indeed fine now.

Can you, please, update the static version occasionally then? I presume this is the one that was used at the time (I do not believe fifteen minutes added more than two hundred votes).

If I happened to have seen it, I bet others do, too.

**Comment by molant** [comment]
The problem is that the static version is going to be always outdated. Even if I change it now, next time we do a push (tomorrow, the day after or in a week) the numbers will still be bad.

**Comment by phistuck** [comment]
Of course they will (be imperfect, not bad as they are now), which is why I wrote "occasionally"...
