### ISSUE TITLE
Clicking features causes scrollTo

### ISSUE THREAD

**Issue by jacobrossi** [MicrosoftEdge/Status#21]
I think in fixing some of the issues with the back history we've broken click-to-expand a feature.  Now, when I click a feature, it expands and then a second later (presumably when the URL is updated) it causes scrollTo. This is jarring. 

I think we should only do the scrollTo (a) during onload and (b) when clicking the back button.

As a related issue, when the scrollTo happens (whether from clicking a feature or by navigating to a routed url), I'm seeing the left color border disappearing:

![bordermissing](https://cloud.githubusercontent.com/assets/2118562/2700401/69546fa8-c412-11e3-9551-2a7f0d0e8efe.png)

**Comment by molant** [comment]
Have you waited for all the features to load before clicking? Once all the features are loaded the scrollTo should be instantaneous (and we cannot insert all the features in one time because of the time it takes, specially in mobile #2).
We needed to add the scrollTo to fix the backbutton navigation issue (#17).

The color border disappearing is something that @dstorey has tried to identify what is happening exactly but it looks as if the whole element shifts to the left (but no CSS is applied). Also it doesn't happen in all browsers :(

**Comment by jacobrossi** [comment]
Even if you wait for them all to load, the scrolling still happens for clicking a feature (yes, it is instant though).  I think we should omit the scroll when clicking a feature (and just expand it in place). But we should do it when hitting the back button OR navigating directly to the URL. 

I'm not familiar with Angular's eventing (e.g. the $locationChangeSuccess event you're using now in #17 ). But it looks like that is firing for both browser navigations (back button, address bar) and when we push a new state into HTML5 History (clicking a feature).

**Comment by molant** [comment]
It is being fired when the location in the address bar changes.
I'll give it another try (didn't found how to do this the last time). The only "issue" is that if a user clicks on a bottom feature he will have to scroll

**Comment by jacobrossi** [comment]
Looks good, thanks!
