### ISSUE TITLE
Inputs are rendered wrong in Firefox

### ISSUE THREAD

**Issue by Studio384** [MicrosoftEdge/Status#256]
Now I get that this might not be a priority, but I've noticed that inputs are rendered wrong for Firefox in comparision with Edge.

The checkboxes are white while they are blue in Edge, and the dropdownlists are blue and spaced very oddly while just normal in Edge.

![knipsel](https://cloud.githubusercontent.com/assets/1693592/9315778/7f9e58ea-4531-11e5-9441-406c4c65bb84.PNG)

**Comment by jacobrossi** [comment]
Hmm, looks like a combination of control styling APIs that aren't supported in FF and possibly some FF bugs.  @melanierichards can you take a look?

**Comment by melanierichards** [comment]
I can fix the spacing issue, but @dstorey should take a look at the other items, he knows a little bit more about how we're gracefully degrading and such.

**Comment by dstorey** [comment]
The spacing issue is the owl pooping on the control, that seems to only hit Firefox on Windows (or at least works on Mac).

The colour issue is something that hits Firefox due to the pseudos, and how we can't cleanly use the MS ones to get the MDL style as we also support -webkit-appearance, and that wipes them out. Need to find away to avoid both issues at same time. But cleaning the owl poop is easy.

**Comment by melanierichards** [comment]
@dstorey yea, I already fixed the spacing issue on the `option` elements.

**Comment by dstorey** [comment]
This is fixed with updates I made to the modern.ie shared styles
