### ISSUE TITLE
Why is Opera status different than Chrome?

### ISSUE THREAD

**Issue by domenic** [MicrosoftEdge/Status#258]
Several features seem to show Chrome as shipping and Opera as under development. I'm a bit confused, as they are the same codebase for web platform feature purposes.

**Comment by jacobrossi** [comment]
These are controlled mostly by the Chromium Dashboard, which has a flag for whether the features are enabled in Opera yet. As I understand it, there can be some lag occasionally and some features are not actually enabled because it requires integration into the UI.  If you see some that are wrong, it most likely is fixed [here](https://github.com/GoogleChrome/chromium-dashboard)
