### ISSUE TITLE
slow font loading results in lame experience

### ISSUE THREAD

**Issue by patrickkettner** [MicrosoftEdge/Status#320]
Using Safari, Chrome, and conference wifi on my phone and the ste is blocked for 30+ seconds waiting on the fonts to download. Any chance we would consider using system fonts? Or perhaps using something like https://github.com/bramstein/fontfaceobserver to give us both?

**Comment by molant** [comment]
That's weird because fonts are on a CDN (woff2 are in a different one than woff and ttf) and in the status page they aren't the biggest resource :/
Woff2 files should be loading from the same one as the JS and CSS. Where you having any issues with those resources?
There was someone else complaining about files in the CDN not being loaded in the VMs page but I don't see any incidence for the CDN in the [Azure Status page](https://azure.microsoft.com/en-us/status/#history).

**Comment by patrickkettner** [comment]
CSS seemed to load nearly instantly. not sure if the JS was working because I didn't know where anything was.

to be clear, everything loaded. just a lot slower.

**Comment by molant** [comment]
That page is one of the heaviest one with the list of features, templates, etc. :(
It is on our backlog to make it faster and slimmer with the VMs page.

Thanks!

**Comment by offece** [comment]
[Excel へようこそ1.xlsx](https://github.com/MicrosoftEdge/Status/files/38485/Excel.1.xlsx)

**Comment by offece** [comment]
[文書1.docx](https://github.com/MicrosoftEdge/Status/files/38492/1.docx)
[文書1.d

ocx](https://github.com/MicrosoftEdge/Status/files/38493/1.docx)

**Comment by dstorey** [comment]
I'm pretty sure this is something to do with moving to the new servers. I've regularly used slow wifi (and low end phone) on the old Azure websites and not had issues with the fonts or the page loading (the page weight is low enough it shouldn't be an issue)

**Comment by jacobrossi** [comment]
Closing this out since the site is now in EdgePortal.
