### ISSUE TITLE
Grid update status

### ISSUE THREAD

**Issue by gsnedders** [MicrosoftEdge/Status#394]
If I'm not mistaken, Edge's impl of Grid is roughly that of the 2011 TR, and the spec has undergone major changes. Would be nice to have something about the status of bringing that up-to-date and unprefixing.

**Comment by jacobrossi** [comment]
Agreed we do need a way to communicate that.  We've had this issue before on how do we say we're updating something we already support. For Indexed DB we were able to "name" the updates (Arrays and Multi Entry Support) as a separate feature to give it a status.  We could describe it via the newer features like subgrid, but I'm not sure that encompasses everything we need to update here.  @gregwhitworth wdyt?

**Comment by gregwhitworth** [comment]
Yeah, the terminology for separate status items would probably be unknown to most web devs because a lot of the other items come from the older template specification that got merged into Grid, and I don't want a separate status item for each item that needs to be updated.

It's worth noting that, you can actually utilize the foundational aspect of grid with the ms prefix and it will work across browsers. The template aspects of grid are syntactic sugar that map to the foundational grid work from IE10. The grid gaps, auto grid, and implicit grid are the largest changes. 

Since you mentioned subgrid, that still needs additional vetting by implementers and approval from the CSSWG since it just recently got the new simpler proposal. That said, I have always been in favor of some sort of statement that we are "revving" the version on the same status item since it is technically the same specification module, and we can detail specifically what we are adding from the specification.

**Comment by cvrebert** [comment]
The Grid status item also doesn't currently have a UserVoice link to https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6514853-update-css-grid

**Comment by saschanaz** [comment]
There is a new item about this now: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/gridupdate/?q=grid

**Comment by alrra** [comment]
> The Grid status item also doesn't currently have a UserVoice link to https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6514853-update-css-grid

It does [now](https://github.com/MicrosoftEdge/Status/blob/79093545bb65e62c7d91e28b7fd8a420721aa541/status.json#L1185).

> There is a new item about this now: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/gridupdate/?q=grid

Yes, closing.

![](https://cloud.githubusercontent.com/assets/1223565/25795166/d091b418-33dc-11e7-8ce9-26be308dbeb4.png)
