### ISSUE TITLE
Sort by status is sometimes random

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#43]
Steps:

Not sure of the exact steps right now, but if you disable some of the interop options then sort by status it gives a random order. Switching between other sorting options and back to "status" will give a different order.

**Comment by dstorey** [comment]
Seems like I can get it to break much more consistently on IE/WinPho. On Chrome or Firefox desktop I haven’t got it to break yet.

**Comment by molant** [comment]
So this happens when the elements haven't been fully inserted and you change the sorting. Because we are inserting them in groups and not all at the same time there is a situation with the timeouts where in some case you can be inserting from the previous sorting and then add from the new one... Just need to clear the timeout if there is one when the insert process starts.
