### ISSUE TITLE
Is Spread operator really supported in edge?

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#453]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/spreades6/?q=spread suggests spread operator is supported.

Spread: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

In Firefox console, open https://developer.microsoft.com/en-us/microsoft-edge/platform/status/spreades6/?q=spread and run `[...document.querySelectorAll('body')]` in console. The result is `[body]`. In Edge `25.10.586.0.0`, it throws `Function expected`.

So which part of the spec is supported and which isn't can you please shed some light?

(btw status page should show the full version as displayed in the browser: `25.10.xxx.y.z`, instead of `10xxx`.. that is just my opinion)

**Comment by FremyCompany** [comment]
It is supported, but NodeList (and its friends) are not iterable in Edge right now (as in, it also does not work with `for...of`). Try `[..."abc"]` as an example of something that should work.

**Comment by ghost** [comment]
@FremyCompany, thanks!

> right now

Do you know if there a open ticket (on GitHub, Connect, UserVoice) where I can track the progress of making NodeList illiterate? Is it on the roadmap somewhere?

**Comment by FremyCompany** [comment]
Looking through issues.microsoftedge.com I found [this entry](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5998615/).

It is marked as External because it is duped to our deliverable, but should be marked as Fixed when we flip our internal deliverable done (or so I'd think; ping @jacobrossi; maybe we should change "External" to "On the backlog" to make it clearer?)

**Comment by jdalton** [comment]
I've created a [user voice entry](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15898300-iterable-nodelists) for it.

**Comment by am11** [comment]
From https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5998615/

> Update: the issue is resolved with NodeList but is still present with HTMLCollections.

This seems to be fixed in Microsoft Edge GA release, however, the error messages seems to need some improvement for invalid case (`querySelector` vs. `querySelectorAll`).

with `[...document.querySelector('body')]`, Firefox:

![image](https://user-images.githubusercontent.com/3840695/45593967-f0272700-b99a-11e8-85de-aba97eb7362d.png)

Edge:

![image](https://user-images.githubusercontent.com/3840695/45593975-07feab00-b99b-11e8-926e-989fccdb9d31.png)

Edge could potentially detect that missing function under question is iterator to give a specific error.

**Comment by arlangalvez** [comment]
@am11 this is a persistent issue.

**Comment by am11** [comment]
@arlangalvez, which one; the lack of better error message or Spread operator support?
Spread operator works for me in latest Edge:

```javascript
// in Edge's Developer Tools
[...document.querySelectorAll('body')]
> [object Array]: [HTMLBodyElement]

navigator.appVersion
> "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19536"
```

**Comment by paddotk** [comment]
`querySelector` gives back an html element (in this case the body), which is not an array. So it makes sense that you cannot deep copy it as such.

**Comment by omhoumz** [comment]
Chome:

<img width="614" alt="Screen Shot 2020-03-30 at 17 43 25" src="https://user-images.githubusercontent.com/7444066/77938672-fdbaae00-72ad-11ea-83e4-994ce8e2c3c4.png">

Edge:

<img width="585" alt="Screen Shot 2020-03-30 at 17 42 19" src="https://user-images.githubusercontent.com/7444066/77938690-0317f880-72ae-11ea-9192-6ec9a3619901.png">

**Comment by molant** [comment]
![image](https://user-images.githubusercontent.com/606594/77957813-f03efd00-7288-11ea-92fc-27be37123b9a.png)
