### ISSUE TITLE
Support ellipsis multi lines

### ISSUE THREAD

**Issue by hieutranagi47** [MicrosoftEdge/Status#463]
Chrome supports -webkit-line-clamp: $number-of-lines to help us show text as short description very nice, but not in IE/Edge/Firefox, so we must estimate number of character then substring by code. I think that why almost developer support Chrome better than the other browser.
.text-2-lines{
  display: block;
  text-align: justify;
  display: -webkit-box;
  max-width: 400px;
  height: 3em; 
  margin: 0 auto;
  font-size: 1em;
  line-height: 1.5em;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
}

<p class="text-2-lines">Labore officia irure esse labore voluptate exercitation ipsum culpa laboris in tempor. Ullamco voluptate magna consequat excepteur occaecat tempor ex esse eu ea anim qui nostrud ex. Nisi enim tempor elit incididunt veniam minim aute consequat.
            Officia ea ipsum ex deserunt velit.</p>

**Comment by gregwhitworth** [comment]
Hi @hieutranagi47 thanks for filing this. Unfortunately, the status page is not where we take feature request but we do on our [uservoice page](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer); feel free to suggest it there.

Now that I've said that, let me tackle the suggestion of `-webkit-line-clamp` that you have proposed. When implementing the `-webkit` properties in our first release of Microsoft Edge we looked at every single one, and this included `-webkit-line-clamp`. Contrary to popular belief, we decided not to implement this for a few reasons:
- It depends on a legacy flexbox implementation
- It is remarkably buggy and gaining interop on a buggy feature is almost impossible so it wasn't something for us to go after
- It doesn't implement it in a very generalized and correct manner either (this leads to the bugs I was referring to earlier)

While we understand the desire for this feature, this type of feature is currently best solved on the application layer via JS if you must have truncation and ellipses added. There are even great small libraries such as [dotdotdot ](http://dotdotdot.frebsite.nl/)that can make this happen with relatively low perf impact, and you get a cross browser solution. In the future, if CSS Houdini becomes what we hope it will, you'll be able to do this in the middle of layout (utilizing the [layout API](https://drafts.css-houdini.org/css-layout-api/)) without having to re-run layout, so it's the best of both worlds.

On the surface this may seem like a trivial problem, "just add three dots" to the last line when I overflow. Unfortunately, it's not as simple as that on the platform level because we have to take everything else into account in a generalized manner. Whereas, a web developer knows the scenario of which they're in and can determine how best to truncate within their given layout. When implementing something like this for the platform we have to take into account all possible scenarios, how do inline tables, flex, and grid work when they're wanting to be truncated? If the content fits but an abspos element overflows do we still truncate? Do we truncate the content within the table cells or flex items? I could go on and on here, but the multitude of tests we threw at it showed how it does not hold up to the level of scrutiny that other standardized approaches face.

I hope that sheds some light on the issue, we do have an item in [L4 of overflow ](https://drafts.csswg.org/css-overflow/#max-lines)to hopefully define this very thing. Currently it has yet to tackle the harder problems I referenced earlier. Usually, the easiest way to design this is to have max-lines not inherit, and be placed directly on the block (display: inline-inside eg: `<p>`) which is exactly how `-o-ellipsis-lastline` approached it. With that said, the majority of use cases we have seen for this, people expect and desire for it to inherit. Thus our quandary.

Finally, thanks for reaching out - if you have any suggestions or ideas on how you would like to solve this I highly recommend providing them to the editors of the overflow specification.

Thanks,
Greg
