### ISSUE TITLE
Firefox has <details>/<summary> supported since v49

### ISSUE THREAD

**Issue by am11** [MicrosoftEdge/Status#480]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/detailssummary suggests `In Development in Firefox`.

GitHub markdown example:

```markdown
<details>
  <summary>Expand to get a treat</summary>
  :cake:
</details>
```

Results in:

<details>
  <summary>Expand to get a treat</summary>
  :cake:
</details>

**Comment by alrra** [comment]
@am11 Data for browsers other than IE and Microsoft Edge comes from the [Chromium Dashboard](https://www.chromestatus.com/features). Mind opening this issue [there](https://github.com/GoogleChrome/chromium-dashboard/issues/new)? Thanks!

---

<details>
  <summary>Expand to get a treat</summary>
  :cake:
</details>
 <br>
⬆️ Nice touch! 👍

**Comment by am11** [comment]
It has been updated upstream https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/wPEQYS9jqdA :)

**Comment by alrra** [comment]
From https://developer.microsoft.com/en-us/microsoft-edge/platform/status/detailssummary/

![](https://cloud.githubusercontent.com/assets/1223565/21317240/f9bf2f2a-c60c-11e6-8413-ea093d1f5493.png)

**Comment by am11** [comment]
@alrra, this is now shipped in Edge stable version 15063. Should we update its status for Edge from `In Development` to `Shipped`?

**Comment by FremyCompany** [comment]
@am11 The DETAILS and SUMMARY elements have not shipped in Edge. There was a version in Preview sometime last month, but it was pulled out because it wasn't complete and we would not have enough time to finish the implementation.

It looks like Github added a polyfill for the element, so it works on Github at this point.

**Comment by mkurz** [comment]
@FremyCompany Will the details and summary elements be ready for the fall update?

**Comment by FremyCompany** [comment]
It's not my team that has been working on this effort but the answer is no, unfortunately.

We do have a policy of slowly cooling down releases, where we take some time to create new features then focus only on bug fixing for couple of months. If a feature isn't ready when we enter this cooling phase, our only option is to remove it in order to not endanger the release. This is what happened here.

I expect the feature to make a return in 2018 but again this is not my team so I can't make any statement here, just educated guesses.

**Comment by mkurz** [comment]
@FremyCompany Thanks for your answer.

**Comment by mkurz** [comment]
@FremyCompany Any updates on the ` <details>/<summary>` support? Will it ship with the March update?

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13120279/ was marked as fixed - however if you don't ship it that bug report should probably be re-opened...

**Comment by molant** [comment]
@mkurz we are working on improving the code that indicates if a bug has been flighted or not in the issue tracker.

**Comment by mkurz** [comment]
@molant So that bug is **not** fixed in the upcoming March release?

**Comment by molant** [comment]
If the big is marked as fixed the is a high chance it will be. What I don't know is if its already fixed in the latest insider flight.

**Comment by FremyCompany** [comment]
This bug had been resolved when the first implementation of DETAILS landed, it is somewhat incorrectly resolved as fixed now since that implementation was pulled off. We don't use bugs to track new features though, so I'll probably just change the resolution status of this bug and post a comment to check the Status page.

I will also update the status page to remove In development for the feature, it's not quite accurate anymore. It's high on the backlog, but not under active development right now.

**Comment by alrra** [comment]
> I will also update the status page to remove In development for the feature, it's not quite accurate anymore.

Done in #573.

Thanks, @FremyCompany!

**Comment by mkurz** [comment]
Thank you for the clarification! :+1:
