### ISSUE TITLE
Add data on web share api

### ISSUE THREAD

**Issue by awebdeveloper** [MicrosoftEdge/Status#496]
Add the new web share api. Currently only available in chrome for android behind a origin trail.

https://developers.google.com/web/updates/2016/10/navigator-share

**Comment by jbmoelker** [comment]
The API is [enabled by default since Chrome 61 for Android](https://developers.google.com/web/updates/2016/09/navigator-share). It's being promoted on popular blogs (like in [Designing for a browserless web on Smashing Magazine](https://www.smashingmagazine.com/2017/11/designing-for-a-browserless-web/#sharing-action)). It's [under consideration in Webkit](https://webkit.org/status/#feature-web-share), but [no official status from Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1312422) yet. There is already an [open issue on UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/31563175-implement-web-share-api). So I think now would be a good time to have the Web Share API added to the Microsoft Edge Status overview.
