### ISSUE TITLE
Doesnt scroll to avoid content overlapping content on mobile

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#52]
Only tested IE mobile so far.

If you have a feature in the URL it scrolls to that feature, but the filter bar overlaps the content.

**Comment by molant** [comment]
This doesn't happen on Chrome Android.
I've look at the code and this is what I'm doing:

```
ele.scrollIntoView();
window.scrollTo(0, (window.pageYOffset - 135));
```

The problem is that pageYOffeset is about 900px when I link to canvas in desktop and in IE Mobile is 0.
Using a timeout just for the scrollTo sometimes fixes the issue (it has to be >= 100ms).

@jacobrossi do you know if this is a bug in IE or am I doing something wrong?

**Comment by dstorey** [comment]
Closing this as the actual website is part of the wider dev.modern.ie now. This should work now.
