### ISSUE TITLE
Expanding feature animation broken in WebKit

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#83]
Steps:
- Expand a feature in WebKit such as Safari 7

Expected:

Smoothly animates to open position

Actual:

when you expand a feature it spasms between open and closed before finishing in the open position in WebKit. Looks really bad.

Broken in Safari (at least in 7, don't have access to 8), iOS, Chrome on Android (at least version 35 according to reports).

@molant was this broken as part of your refactoring or was it already broken in @jacobrossi’s code?

**Comment by molant** [comment]
I see the opposite error (no animation when closing) in IE11 (desktop and mobile), Chrome and Firefox.
I have no idea on when this was broken but I only add/remove a class since the beginning... Could it be that:
- Something got removed in the CSS clean up process?
- because now we are just changing the display to block and animate the rest maybe the browsers are doing some "performance" optimizations and jump to the end of the animation?

Still, none of the above explain why we see different animations :S

**Comment by dstorey** [comment]
I don't think there was any CSS clean up after the expanding logic was changed to stop the content overlapping.

**Comment by molant** [comment]
I saw the animation on a mac and it is definitely not the same as I'm seeing on Windows. I really don't know what is going on :S

**Comment by jacobrossi** [comment]
Going to close this one for now, doesn't look like a major issue and I don't repro on my machine.

**Comment by dstorey** [comment]
I still see this as an issue (on Safari 7) hopefully solved once yosmite comes out (don't have access to saf 8 builds)
