### ISSUE TITLE
Add  contributing.md file

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#90]
We should add a  contributing.md file so when a dev makes a PR to the project he will have access to the project's contributing guide.

**Comment by jacobrossi** [comment]
We can probably just split off the contributing section in the readme.

**Comment by am11** [comment]
If applicable, you can copy some bits from WebEssentials's guidelines: https://github.com/madskristensen/WebEssentials2013/blob/master/CONTRIBUTING.md 

:-)

**Comment by molant** [comment]
I don't know how the MS-PL license works with the Apache 2 so for now I think we are going to take the sections in Licensing and add a couple more things but thank you :)

**Comment by am11** [comment]
@molant, yqwc!

As a power-user, I have three UX related points (all inspired by non-IE browsers):
- Ctrl+browser-back-or-forward button shortcut to open previous/forward page in new tab.
- Ctrl+0 bring zoom level to normal. If 0 is pressed on qwerty keyboard, it works, but doesn't work if zero was pressed on num-pad.
- `Paste and Go (Ctrl + Shift + L)` entry in address bar's context menu (available in modern but missing in classic desktop version). Hidden shortcut `Ctrl + Shift + L` works in classic version though.

Like many folks out there, if you too enjoy these features in other browsers then please ask UX team to add these in vNext of IE.

Thanks in anticipation!

**Comment by dstorey** [comment]
Hi @am11. Thanks for the feedback. UX issues for the browser itself are not tracked in this GitHub Issues. Until we have a better solution, it would be best to file individual bugs at connect.microsoft.com/IE/

**Comment by jacobrossi** [comment]
@molant I like the change. I updated it to remove the contribution guidelines from the README so we don't have to maintain both.

**Comment by am11** [comment]
@dstorey, thanks. Unfortunately the _proper procedure_ suggests that even if we apply round-robin scheduling, these kind of issues will never get a turn (due to their insignificance?) :)

To wit, those are already on Connect for years now:
- [One missing and another poorly implemented shortcut](https://connect.microsoft.com/IE/feedback/details/708803/one-missing-and-another-poorly-implemented-shortcut)
- [Like IE10 Metro, provide "Paste and Go" option in IE10 Desktop](https://connect.microsoft.com/IE/feedback/details/747190/like-ie10-metro-provide-paste-and-go-option-in-ie10-desktop)

It doesn't seem like even on Connect, UX issues are heard. Those shortcuts are available in Chrome, Firefox, Opera, Safari and all browsers which support tabs. It might not be a show stopper, but for people who spend most of their day time with browsers; its a big miss!

**Comment by jacobrossi** [comment]
@am11 This repository is not monitored by the team responsible for the IE app user interface.  That team does actively monitor Connect and your feedback has been heard. 

-Jacob

PS -  If it helps you, "Go to copied address" is at least available in the web page context menu in desktop IE.
